language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  exclude:
    - php: 7.0
      env: LARAVEL_VERSION=5.6.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - travis_retry composer update --no-interaction --prefer-source
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;

script:
  - vendor/bin/phpunit

env:
  - LARAVEL_VERSION=5.5.*
  - LARAVEL_VERSION=5.6.*
